### ISSUE TITLE
PINN matrices cannot be multiplied

### ISSUE THREAD

**Issue by wszs8921** [pdebench/PDEBench#15]
Hi,I met this problem when i used PINN and ran train_models_forward.py. it showed that two matrices cannot be multiplied

``` Compiling model...
'compile' took 0.000202 s

Training model...

Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/xxx/PDEBench/pdebench/models/train_models_forward.py", line 232, in main
    run_training_PINN(
  File "/home/xxx/PDEBench/pdebench/models/pinn/train.py", line 472, in run_training
    test_pred, test_gt, model_name = _run_training(scenario, epochs, learning_rate, model_update, flnm,
  File "/home/xxx/PDEBench/pdebench/models/pinn/train.py", line 409, in _run_training
    losshistory, train_state = model.train(
  File "/home/xxx/anaconda3/envs/PDEBench/lib/python3.9/site-packages/deepxde/utils/internal.py", line 22, in wrapper
    result = f(*args, **kwargs)
  File "/home/xxx/anaconda3/envs/PDEBench/lib/python3.9/site-packages/deepxde/model.py", line 427, in train
    self._test()
  File "/home/xxx/anaconda3/envs/PDEBench/lib/python3.9/site-packages/deepxde/model.py", line 559, in _test
    ) = self._outputs_losses(
  File "/home/xxx/anaconda3/envs/PDEBench/lib/python3.9/site-packages/deepxde/model.py", line 356, in _outputs_losses
    outs = self.outputs_losses(training, inputs, targets)
  File "/home/xxx/anaconda3/envs/PDEBench/lib/python3.9/site-packages/deepxde/model.py", line 229, in outputs_losses
    outputs_ = self.net(self.net.inputs)
  File "/home/xxx/anaconda3/envs/PDEBench/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxx/anaconda3/envs/PDEBench/lib/python3.9/site-packages/deepxde/nn/pytorch/fnn.py", line 33, in forward
    x = self.activation(linear(x))
  File "/home/xxx/anaconda3/envs/PDEBench/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxx/anaconda3/envs/PDEBench/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (10024x2 and 1x40)

```

And here is the config that i used for training
``` defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

args:
  model_name: 'PINN'
  scenario: 'pde1D'
  model_update: 500
  filename: '1D_Advection_Sols_beta0.1.hdf5'
  epochs: 15000
  input_ch: 2
  output_ch: 1
  learning_rate: 1.e-3
  root_path: './data'
  val_num: 10
  if_periodic_bc: True
  period: 5000
  val_time: 2.0
  val_batch_idx: 10
  aux_params: [ 0.1 ]
  seed: '0000'
```
thanks and i need your help.

**Comment by mtakamoto-D** [comment]
Hi. 
Thank you very much for your kind notice. 
I have debugged our code, so please try the latest version. 

@timothypraditia @leiterrl  I have modified PINN's part of train_models_forward.py, adding several missing input parameters for my part training. So please check it if it does not affect your part.
And I have also added PINN examples in run_forward_1D.sh

Note that changing models/config.yaml causes a serious problem. 
So, please leave it as it as, and only change models/config/args/config*yaml  if you want to try a new parameters.

Thank you again for your kind notice!

**Comment by wszs8921** [comment]
Thanks for your reply and it works indeed.But there is another problem.After using
```
CUDA_VISIBLE_DEVICES='0' python3 train_models_forward.py +args=config_pinn_pde1d.yaml ++args.filename='1D_Advection_Sols_beta0.1.hdf5' ++args.aux_params=[0.1]
```
I got the pickle file. Then I tried to get the result and ran the analyse_result_forward.py.There was a problem
```
['./1D', 'Advection', 'Sols', 'beta0.1', 'PINN']
Traceback (most recent call last):
  File "/home/aidawei/PDEBench/pdebench/models/analyse_result_forward.py", line 235, in <module>
    main()
  File "/home/aidawei/PDEBench/pdebench/models/analyse_result_forward.py", line 216, in main
    width = 0.5/(num_models-1)
ZeroDivisionError: float division by zero
```
how can I process this problem to get the result?

**Comment by timothypraditia** [comment]
Hi @wszs8921 , the error was caused by the plotting script, since we used it to plot comparison of multiple models.
I have fixed the bug. Could you please check if it's working now and if so, could you please also close the issue?
Many thanks for spotting this! :D

**Comment by wszs8921** [comment]
Thanks,It's working now and I have closed the issue.
