### ISSUE TITLE
Downloading the data

### ISSUE THREAD

**Issue by JeanKossaifi** [pdebench/PDEBench#2]
Dear authors, I am getting an error when trying to download the data:
```
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="config/", config_name="config")
/.../PDEBench/venv/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/next/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
Error executing job with overrides: []
Traceback (most recent call last):
  File "/.../PDEBench/pdebench/data_download/download.py", line 42, in main
    api = NativeApi(os.getenv("DATAVERSE_URL"), os.getenv("DATAVERSE_API_TOKEN"))
  File "/.../PDEBench/venv/lib/python3.9/site-packages/pyDataverse/api.py", line 639, in __init__
    super().__init__(base_url, api_token, api_version)
  File "/.../PDEBench/venv/lib/python3.9/site-packages/pyDataverse/api.py", line 61, in __init__
    raise ApiUrlError("base_url {0} is not a string.".format(base_url))
pyDataverse.exceptions.ApiUrlError: base_url None is not a string.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
I left the configuration as it is provided in the repo.

**Comment by leiterrl** [comment]
Hi Jean,

for the download to work you will currently need to provide an `.env` file in the `data_download` folder.  A template called `example.env` is provided. I will try to clarify this in the README.

However, you will also need to create a DaRUS API_TOKEN which is only available to authenticated users. I will look into whether it's possible to get around this restriction as it seems quite unnecessary for just downloading.

**Comment by leiterrl** [comment]
Alright, I just pushed a simplified download script that should work without any API_TOKEN now.

**Comment by JeanKossaifi** [comment]
Thanks @leiterrl!
