### ISSUE TITLE
An error when using the CUDA=11.7

### ISSUE THREAD

**Issue by HUST-AI-HYZ** [pdebench/PDEBench#55]
Thanks for your good work. When I am training the FNO with the default cuda/torch setting (conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia), it will lead to an error like that: 

Traceback (most recent call last):
  File "pdebench/models/train_models_forward.py", line 326, in <module>
    main()
  File "/scratch/yzhu/anaconda3/envs/myenv/lib/python3.8/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/scratch/yzhu/anaconda3/envs/myenv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/scratch/yzhu/anaconda3/envs/myenv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/scratch/yzhu/anaconda3/envs/myenv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/scratch/yzhu/anaconda3/envs/myenv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/scratch/yzhu/anaconda3/envs/myenv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/scratch/yzhu/anaconda3/envs/myenv/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/scratch/yzhu/anaconda3/envs/myenv/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/scratch/yzhu/anaconda3/envs/myenv/lib/python3.8/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "pdebench/models/train_models_forward.py", line 223, in main
    run_training_FNO(
  File "/scratch/yzhu/TBv2-PDEBench/pdebench/models/fno/train.py", line 339, in run_training
    im = model(inp, grid)
  File "/scratch/yzhu/anaconda3/envs/myenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/yzhu/TBv2-PDEBench/pdebench/models/fno/fno.py", line 221, in forward
    x1 = self.conv0(x)
  File "/scratch/yzhu/anaconda3/envs/myenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/yzhu/TBv2-PDEBench/pdebench/models/fno/fno.py", line 163, in forward
    x_ft = torch.fft.rfft2(x)
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR

**Comment by kmario23** [comment]
> conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia

Please upgrade your pytorch version to cuda 11.8 build or newer, and that should resolve the `RuntimeError` of `cuFFT`.
