### ISSUE TITLE
Darcy flow issue for "AttributeError: 'int' object has no attribute 'item'"

### ISSUE THREAD

**Issue by 321hu** [pdebench/PDEBench#77]
I use the config file [config_darcy.yaml](https://github.com/pdebench/PDEBench/blob/main/pdebench/models/config/config_darcy.yaml) to run the code:

`python train_models_forward.py +args=config_darcy.yaml ++args.model_name='FNO' ++args.filename='2D_DarcyFlow_beta1.0_Train.hdf5' ++args.data_path='../data'`

But there is an error:

```
Error executing job with overrides: ['+args=config_darcy.yaml', '++args.model_name=FNO', '++args.filename=2D_DarcyFlow_beta1.0_Train.hdf5', '++args.data_path=../data']
Traceback (most recent call last):
  File "D:\Learning\Graduate\PDEBench\pdebench\models\train_models_forward.py", line 163, in main
    run_training_FNO(
  File "D:\Learning\Graduate\PDEBench\pdebench\models\../..\pdebench\models\fno\train.py", line 257, in run_training
    train_l2_step += loss.item()
AttributeError: 'int' object has no attribute 'item'
````

**Comment by 321hu** [comment]
I know what happened.............

I added `++args.training_type='signle'` in the command and the error didn't occur anymore.

But why should I add the `args` additionally???

**Comment by kmario23** [comment]
Have a look at the relevant issue, https://github.com/pdebench/PDEBench/issues/48.

Yes, you have to update the relevant config file of the PDE in the line you mentioned.
