### ISSUE TITLE
Config files / running the example code

### ISSUE THREAD

**Issue by GeoffNN** [pdebench/PDEBench#8]
Hi! 
Great work, it's pretty great to have dataloaders set up for all these different PDE examples.

I've been struggling with running the example code, e.g. on Advection data, which is the default one which the data_download file gets. (Btw, the downloader doesn't respect the config file data paths, which is a bit confusing for a new user.)

I started by trying 

`CUDA_VISIBLE_DEVICES='2' python train_models_forward.py +args=config.yaml`

and got the following error : `In 'config': Could not find 'args/config.yaml'`
My understanding is that I had to change `config.yaml` with `config_pinn_pde1d.yaml`, but I'm not entirely sure.

Once I did so, and changed the `filename` and `root_path` in my config, I got an  error "local variable 'timedomain' referenced before assignment", which seems due to how the filename is parsed.  https://github.com/pdebench/PDEBench/blob/f8c8493692e3290f1435b99e4eae66f224938414/pdebench/models/pinn/train.py#L217 It would be nice to add a `raise ValueError` around this line ; and perhaps to be more explicit in what filenames are allowed or not.

After fixing this, I got a shape error here https://github.com/pdebench/PDEBench/blob/f8c8493692e3290f1435b99e4eae66f224938414/pdebench/models/pinn/utils.py#L354, which I'm not sure how to fix. It seems that due to the indexing using `val_batch_idx`, the tensor `elf.data_output` becomes 1d. I'm surprised here that the tensor isn't 3D to start with (I checked, and `h5_file['tensor']` is shape (201, 1024).

Perhaps I downloaded the wrong files? Here is the config that I used for downloading (I didn't modify it) : 

```
args:
    filename: 'Advection_beta'
    dataverse_url: 'https://darus.uni-stuttgart.de'
    dataset_id: 'doi:10.18419/darus-2986'
    data_folder: 'data'
```

Any help would be greatly welcome!!

**Comment by GeoffNN** [comment]
I'm also getting errors when trying to run the scripts in `run_forward_1D.sh`.

For instance, running this
```
CUDA_VISIBLE_DEVICES='2' python3 train_models_forward.py +args=config.yaml ++args.filename='1D_Burgers_Sols_Nu0.001.hdf5' ++args.model_name='FNO'
```
 from the `pdebench/models` folder gives
```
In 'config': Could not find 'args/config.yaml'

Available options in 'args':
        config_1DCFD
        config_2DCFD
        config_3DCFD
        config_Darcy
        config_ReacDiff
        config_diff-react
        config_diff-sorp
        config_pinn_CFD1d
        config_pinn_diff-react
        config_pinn_diff-sorp
        config_pinn_pde1d
        config_pinn_swe2d
        config_rdb
Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file:///home/ubuntu/PDEBench/pdebench/models/config
        provider=schema, path=structured://
```

**Comment by timothypraditia** [comment]
Hi there, could you try removing the `+args=config.yaml` argument?
I think this is because we already specified `config_path="config"` and `config_name="config"` in the code, so it refers to the config.yaml file inside the config directory.
The way we intended the config to be used is by copying the arguments from the provided config file depending on the problem to be solved, and pasting them to the config.yaml file.
Another option would be to try changing your argument into `+args=<specific_config_filename>`, with the specific_config_filename is e.g. config_1DCFD.yaml
Please let us know if this works.

**Comment by GeoffNN** [comment]
Hi! 

Thanks for the comment. This seems to work for this step, but unfortunately I still run into some errrors.

1. When running using Burgers, I get a strange 
```
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/home/ubuntu/PDEBench/pdebench/data/1D/Burgers/1D_Burgers_Sols_Nu0.04.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)  
```
although the file is definitely in the correct location.

2. When running on DarcyFlow, I get a pyTorch dataloader issue:
```

Error executing job with overrides: ['++args.filename=1D_Advection_Sols_beta4.0.hdf5', '++args.model_name=FNO', '++args.base_path=/home/ubuntu/PDEBench/pdebench/data/1D/Advection/Train/']
Traceback (most recent call last):
  File "/home/ubuntu/PDEBench/pdebench/models/train_models_forward.py", line 169, in main
    run_training_FNO(
  File "/home/ubuntu/PDEBench/pdebench/models/fno/train.py", line 186, in run_training
    for xx, yy, grid in train_loader:
  File "/opt/conda/envs/pdebench_cu116/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/opt/conda/envs/pdebench_cu116/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/opt/conda/envs/pdebench_cu116/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/opt/conda/envs/pdebench_cu116/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/pdebench_cu116/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/pdebench_cu116/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/pdebench_cu116/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/PDEBench/pdebench/models/fno/utils.py", line 360, in __getitem__
    return self.data[idx,...,:self.initial_step,:], self.data[idx], self.grid
RuntimeError: CUDA error: initialization error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
which I haven't been able to debug.

Could you please share which version of pytorch you tested the library on?

Thanks!

**Comment by timothypraditia** [comment]
1. Could you please share which line of code from which script leads to the error? And could you also recheck if the file is indeed in the specified directory and is not corrupted?
2. Could you try either using CPU only or set the number of workers=1 and see if it works (and also to have a clearer error message)? @mtakamoto-D : could you please check on the arguments for DarcyFlow and the version of PyTorch you’re using?

**Comment by mtakamoto-D** [comment]
Based on our experience, it occurs when performing training on GTX 3090 GPU with cuda11.3+. 
Can you please replace the following modification on the corresponding part in train.py
(e.g., if FNO, L101--104)?

```
gen_device='cuda'

train_loader = torch.utils.data.DataLoader(train_data, batch_size=batch_size,                            
                                                                num_workers=num_workers, shuffle=True,                                           
                                                                generator=torch.Generator(device=gen_device))

val_loader = torch.utils.data.DataLoader(val_data, batch_size=batch_size,                                         
                                                             num_workers=num_workers, shuffle=False,                                         
                                                             generator=torch.Generator(device=gen_device))
```

**Comment by GeoffNN** [comment]
Hi, thanks for the reply. Unfortunately I get the same error.

I'm using V100 GPUs with CUDA 11.7 (also tried 11.6).

**Comment by timothypraditia** [comment]
Hi there,

Yes, the single_file argument should be set to True for the Burgers dataset. I assume that line 184 in the fno/utils.py script would give an error since the file type is hdf5 and not h5.
My suspicion is that the error is caused by the mismatch of dimension, because the arguments for the FNO set up (num_channels, modes, and width) might be wrong.

@mtakamoto-D Could you please provide the config arguments for the Burgers dataset and change the assert statement to accept also hdf5 file (not only h5)?

**Comment by mtakamoto-D** [comment]
@timothypraditia 
Seemingly I added the assert sentence not to confuse multiple data with .h5 (mine uses .hdf5). 
For the user friendliness, that assert sentence should be erased. 
If you agree with it, I would commented out them.

**Comment by timothypraditia** [comment]
@mtakamoto-D Ah I see, then I think the assert command should be fine.
Could you please also provide the config file for the Burgers dataset training?

**Comment by mtakamoto-D** [comment]
Concerning config file, 1D Advection/Burgers/Reaction-Diffusion eqs. are assumed to use the same config file: 
`config/args/config.yaml`
Do we copy for each equations, though the contents are the same?

**Comment by timothypraditia** [comment]
@GeoffNN: Makoto will provide the config files as soon as possible. In the meantime, could you try to copy the arguments in the file [config_ReacDiff.yaml](https://github.com/pdebench/PDEBench/blob/main/pdebench/models/config/args/config_ReacDiff.yaml) to the arguments in the file [config.yaml](https://github.com/pdebench/PDEBench/blob/main/pdebench/models/config/config.yaml) and then try to run it?

**Comment by mtakamoto-D** [comment]
Hi there. 
I have uploaded the missing config file for 1D advection/burgurs equations with modification of run_forward_1D.sh
Can you please update your local repository to the newest one?

**Comment by GeoffNN** [comment]
Hello,

I haven't had the bandwidth recently to try; I'll keep you posted as soon as I do.
Happy holidays!
